
type="real";function typechanged(value){type=value;optionrange(true);}
lastupdate="";var southWest=L.latLng(11,27),northEast=L.latLng(39,69),bounds=L.latLngBounds(southWest,northEast);map=L.map('map',{zoomSnap:1,maxBounds:bounds,minZoom:4,fullscreenControl:localStorage.sittings_fullscreen=='true',fullscreenControlOptions:{position:'topleft'}});map.setView(new L.LatLng(localStorage.lat||southWest.lat/2+northEast.lat/2,localStorage.lng||southWest.lng/2+northEast.lng/2),localStorage.zoom||4);if(localStorage.myloc!='false')
map.addControl(L.control.locate({strings:{title:"إظهار موقعي"},keepCurrentZoomLevel:true,flyTo:true,cacheLocation:true,locateOptions:{watch:true,enableHighAccuracy:true}}));if(localStorage.search!='false')
map.addControl(new L.Control.Search({url:'https://nominatim.openstreetmap.org/search?format=json&q={s}',jsonpParam:'json_callback',propertyName:'display_name',propertyLoc:['lat','lon'],autoCollapse:true,firstTipSubmit:true,autoType:true,minLength:2,position:'topright',zoom:9}));setInterval(function(){var ll=map.getCenter();var z=map.getZoom();localStorage.lat=ll.lat;localStorage.lng=ll.lng;localStorage.zoom=z;},1000);if(localStorage.sittings_dayandnight=='true'){var t=L.terminator();t.addTo(map);setInterval(function(){updateTerminator(t)},500);}
function getcurrentOpacity(){var z=map.getZoom();if(z<5)return(localStorage.opacity_s||70)/100;if(localStorage.auto_opacity=='false')return(localStorage.opacity_s||70)/100;if(z>10)z=10;var p=g(5,10,z)/5;var c=(localStorage.opacity_s||70)/100;return c-c*p;}
map.on('zoomend',function(){$('.ri').animate({opacity:getcurrentOpacity()},'fast');});markerGroup=L.layerGroup().addTo(map);function show(){document.getElementById("info").style.display="block";}
function getUrl(url){var canvas=document.createElement("canvas");var olddata=localStorage.getItem("cache"+url);if(olddata!==null)return olddata;var img=new Image();img.crossOrigin="anonymous";img.onload=function(){canvas.width=img.width;canvas.height=img.height;var ctx=canvas.getContext("2d");ctx.drawImage(img,0,0);ctx.drawImage(this,0,0,canvas.width,canvas.height);var dataURL=canvas.toDataURL("image/png");localStorage.setItem("cache"+url,dataURL);};img.src=url;return url;}
try{if(getvalue("tile").indexOf('{s}.yanbuweather.com')!=-1){localStorage.tile='https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png';}}catch(a){}
Layer=L.tileLayer.fallback(SourceTileURL((getvalue("tile")||'https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png')),{detectRetina:localStorage.detectRetina!="false",maxZoom:18,hash:function(data){return data.x%4+(data.y%4)*4;}});map.addLayer(Layer);setTimeout(function(){if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){if(typeof Layer2!=='undefined')map.removeLayer(Layer2);Layer2=L.tileLayer.fallback(SourceTileURL('https://www.yanbuweather.com/pages/RainRadar/darkb_tiles/img/{z}-{x}-{y}.png'),{detectRetina:localStorage.detectRetina!="false",maxZoom:18,hash:function(data){return data.x%4+(data.y%4)*4;},zIndex:999});map.addLayer(Layer2);}},5000);function removeall(){map.removeLayer(markerGroup);markerGroup=L.layerGroup().addTo(map);}
function markerOnClick(){}
function onLocationFound(e){}
function op(){if(document.getElementById("ab").value=="a"){document.getElementById("ab").value="b";document.getElementById("ab").innerHTML="ثابت";document.getElementById("hour").disabled=true;if(typeof forecast!=='undefined')map.removeLayer(forecast);if(typeof arrows!=='undefined')map.removeLayer(arrows);if(typeof speeds!=='undefined')map.removeLayer(speeds);}else{document.getElementById("ab").value="a";document.getElementById("ab").innerHTML="متحرك";document.getElementById("hour").disabled=false;document.getElementById("hour").selectedIndex=0;}
update();}
map.on('layeradd',function(e){});function checklayers(){if((localStorage.sittings_forecast=='true'||false)&&document.getElementById("hour").selectedIndex<=1&&type!="forecast"){var imageUrl=("getforecast.php"+document.getElementById("hour").value),imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];if(typeof forecast!=='undefined')map.removeLayer(forecast);forecast=L.imageOverlay(imageUrl,imageBounds,{opacity:0.34,zIndex:6});forecast.addTo(map);}else{if(typeof forecast!=='undefined')map.removeLayer(forecast);}
if((localStorage.sittings_arrows=='true'||false)&&document.getElementById("hour").selectedIndex<=1&&type!="forecast"){imageUrl=("getarrows.php"+document.getElementById("hour").value),imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];if(typeof arrows!=='undefined')map.removeLayer(arrows);arrows=L.imageOverlay(imageUrl,imageBounds,{opacity:0.5,zIndex:7});arrows.addTo(map);}else{if(typeof arrows!=='undefined')map.removeLayer(arrows);}
if((localStorage.sittings_speeds=='true'||false)&&document.getElementById("hour").selectedIndex<=1&&type!="forecast"){imageUrl=("getspeeds.php"+document.getElementById("hour").value),imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];if(typeof speeds!=='undefined')map.removeLayer(speeds);speeds=L.imageOverlay(imageUrl,imageBounds,{opacity:1,zIndex:8});speeds.addTo(map);}else{if(typeof speeds!=='undefined')map.removeLayer(speeds);}}
imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];function getRadarUrl(){if(localStorage.eradar=="true")return "/pages/accwradar/get.php";return "get.php";}
OO=0;XX=new Date().getTime();function update(){if(document.getElementById("ab").value=="a"){oldSrc="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7";if(typeof image!=='undefined')oldSrc=$('.ri')[0].src;var imageUrl=(getRadarUrl()+document.getElementById("hour").value+"&alpha="+(localStorage.sittings_background!='true'));if(typeof image2!=='undefined'&&image2._url===imageUrl){if(image2.getElement().complete&&image2.getElement().naturalHeight===0){image2.getElement().src=imageUrl;}
return;}
if(typeof image==='undefined')image=L.imageOverlay(oldSrc,imageBounds,{opacity:getcurrentOpacity(),zIndex:5,className:'ri'}),image.addTo(map);if(typeof image2==='undefined')image2=L.imageOverlay(imageUrl,imageBounds,{opacity:0,zIndex:6,className:'ri2'}),image2.addTo(map);showloading();$('.ri2')[0].src=oldSrc;var img=new Image();img.onload=function(){image2.setUrl(oldSrc);image.setUrl(imageUrl);$('.ri2').css('opacity',getcurrentOpacity()).stop().animate({opacity:0},{complete:function(){image2.setUrl("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");}},'slow');$('.ri').css('opacity',0).stop().animate({opacity:getcurrentOpacity()},'slow');hideloading();}
img.src=imageUrl;checklayers();if($('.cloud').length)$('.cloud')[0].src="getclouds.php"+document.getElementById("hour").value;else check_clouds();}else{var nextIndex=document.getElementById("hour").selectedIndex-1;if(nextIndex<0)nextIndex=document.getElementById("hour").length-1;var currentIndex=document.getElementById("hour").selectedIndex;if($('.cloud').length&&$(".cloud").isLoaded()){clouds.setUrl("getclouds.php"+document.getElementById("hour").value);}
var currentSrc=getRadarUrl()+document.getElementById("hour")[currentIndex].value+"&alpha="+(localStorage.sittings_background!='true');var nextSrc=getRadarUrl()+document.getElementById("hour")[nextIndex].value+"&alpha="+(localStorage.sittings_background!='true');if(typeof image==='undefined')image=L.imageOverlay(currentSrc,imageBounds,{opacity:getcurrentOpacity(),zIndex:5,className:'ri'}),image.addTo(map);if(typeof image2==='undefined')image2=L.imageOverlay(nextSrc,imageBounds,{opacity:0.001,zIndex:6,className:'ri2'}),image2.addTo(map);if(image._url===currentSrc&&image2._url===nextSrc){console.log("second call");var t=Math.max(0,XX-new Date().getTime());if(image.getElement().complete&&image2.getElement().complete){console.log("img download completed");if(t==0){image.setOpacity(0.001);image2.setOpacity(getcurrentOpacity());setTimeout(function(){document.getElementById("hour").selectedIndex=nextIndex;update();},(Number(localStorage.speed)||150));}else{setTimeout(function(){update();},t);}}else{setTimeout(function(){update();},t);}}else{console.log("first call");image.setUrl(currentSrc);image.setOpacity(getcurrentOpacity());image2.setUrl(nextSrc);image2.setOpacity(0.01);setTimeout(function(){update();},(Number(localStorage.speed)||150));XX=new Date().getTime()+(Number(localStorage.speed)||150);}}}
$.fn.extend({isLoaded:function(){return this.prop("complete");}})
function is_cached(src){var image=new Image();image.src=src;return image.complete;}
function showloading(){document.getElementById("loading").style.visibility="visible";}
function hideloading(){document.getElementById("loading").style.visibility="hidden";}
var infoButton=L.control.infoButton({linkTitle:'إعدادات',title:'<h2>إعدادات</h2>',html:`
<div style="direction:rtl">التحميل: <br>
  <img src="leaflet/savegif.svg?2" style="height: 17px;"> تحميل الصورة المتحركة لآخر: <select id="gif_range" onchange="localStorage.gif_range=this.value;">
    <option value="1">ساعة </option>
    <option value="2">ساعتين </option>
    <option value="3">3 ساعات </option>
    <option value="4">4 ساعات </option>
    <option value="5">5 ساعات </option>
    <option value="6">6 ساعات</option>
    <option value="12">12 ساعة </option>
  </select>
  <br>
  <img src="leaflet/savegif.svg?2" style="height: 17px;">سرعة تحريك الصورة: <select id="gif_speed" onchange="localStorage.gif_speed=this.value;">
    <option value="20">أسرع ما يمكن</option>
    <option value="45" selected="">سريع</option>
    <option value="75">متوسط</option>
    <option value="500">بطيء</option>
  </select>
  <br>الطبقات: <br>
  <input type="checkbox" id="arrows" onchange="localStorage.sittings_arrows=this.checked;update();">إظهار اتجاه حركة السحب <span style="color: blue;font-size:small;">تجريبي</span>
  <br>
  <input type="checkbox" id="forecast" onchange="localStorage.sittings_forecast=this.checked;update();">إظهار مسار السحب <span style="color: blue;font-size:small;">تجريبي</span>
  <br>
  <input type="checkbox" id="speeds" onchange="localStorage.sittings_speeds=this.checked;update();">إظهار سرعة حركة السحب <span style="color: blue;font-size:small;">تجريبي وجديد</span>
  <br>
  <input type="checkbox" id="background" onchange="localStorage.sittings_background=this.checked;update();">خلفية مظلمة <br>
  <input type="checkbox" id="thqafi" onchange="localStorage.thqafi=this.checked;check_topo(this);">إظهار خريطة الثقافي <span style="color: blue;font-size:small;">ميزة جديدة</span>
  <br>
  <div class="pro">
    <input type="checkbox" id="gcs" onchange="localStorage.gcs=this.checked;check_topo(this);">إظهار خريطة هيئة المساحة السعودية <span style="color: blue;font-size:small;"> PRO</span>
    <br>
  </div>
  <input type="checkbox" id="water" onchange="localStorage.water=this.checked;check_water();">إظهار الأودية ومجاري السيول <span style="color: blue;font-size:small;">ميزة جديدة</span>
  <br>مدى الوقت: <select id="options_n" onchange="localStorage.options_n=this.value;lastupdate=0;optionrange()">
    <option value="12">ساعة واحدة</option>
    <option value="24">ساعتان</option>
    <option value="36" selected="">3 ساعات</option>
    <option value="72">6 ساعات</option>
    <option value="144">12 ساعة</option>
    <option value="288">يوم واحد</option>
    <option value="576">يومان</option>
    <option value="864">ثلاثة أيام</option>
  </select>
  <br>شكل الخريطة: <select id="tile" onchange="localStorage.tile=this.value;changetile();">
    <option value="https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png" selected="">Mapy.cz </option>
    <option value="https://www.yanbuweather.com/pages/RainRadar/tracestrack_tiles/img/{z}-{x}-{y}.png">tracestrack (طبوغرافية)</option>
    <option value="https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png" selected="">خريطة مظلمة + السحب</option>
    <option value="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png">OpenStreetMap </option>
    <option value="https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png">OpenTopoMap </option>
    <option value="https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png?lang=ar">Wikimedia maps</option>
    <option value="https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png">OpenStreetMap.HOT</option>
    <option value="http://i{hash}.wikimapia.org/?x={x}&amp;y={y}&amp;zoom={z}&amp;r=7071412&amp;type=&amp;lng=10">wikimapia</option>
    <option value="https://www.yanbuweather.com/pages/RainRadar/meteored_tiles/img/{z}-{x}-{y}.png">قمر صناعي</option>
  </select>
  <br>
  <input type="checkbox" id="clouds" onchange="localStorage.clouds=this.checked;check_clouds();">إظهار السحب والغيوم
  <br>
  <input type="checkbox" id="eradar" onchange="localStorage.eradar=this.checked;update();">تفعيل بديل الرادار <span style="color: blue;font-size:small;">تجريبي وجديد</span>
  <br>تعتيم صورة الرادار: <input type="number" min="0" max="100" value="70" id="input-opacity" onchange="localStorage.opacity_s=this.value;update();">
  <br>
  <input type="checkbox" id="autoopacity" onchange="localStorage.auto_opacity=this.checked;update();" checked="">شفافية آلية <br>سرعة التحريك: <select id="speed" onchange="localStorage.speed=this.value;">
    <option value="50" selected="">أسرع ما يمكن</option>
    <option value="100">سريع</option>
    <option value="300">متوسط</option>
    <option value="1500">بطيء</option>
  </select>
  <br>إظهار الملحقات: <br>
  <input type="checkbox" id="fullscreen" onchange="localStorage.sittings_fullscreen=this.checked;UpdatePage=true;">ملء الشاشة <br>
  <input type="checkbox" id="search" onchange="localStorage.search=this.checked;UpdatePage=true;" checked="">البحث عن مكان <br>
  <input type="checkbox" id="myloc" onchange="localStorage.myloc=this.checked;UpdatePage=true;" checked="">موقعي <br>
  <input type="checkbox" id="dayandnight" onchange="localStorage.sittings_dayandnight=this.checked;UpdatePage=true;">إظهار الليل والنهار <br>
  <input type="checkbox" id="detectRetina" onchange="localStorage.detectRetina=this.checked;UpdatePage=true;" checked="">جودة خريطة عالية (أسماء مدن بخط أصغر) <br>
  <hr> جميع الحقوق محفوظة © yanbuweather.com
</div>
`}).addTo(map);setInterval(function(){if(new Date().getTime()>updateAt)location.reload(true);},10000);XMLhttpreq=function(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml3.XMLHTTP")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(a){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(a){}return null}();function optionrange(s){var options_n=localStorage.options_n||12;setCookie("options_n",options_n);xhr=XMLhttpreq;xhr.onreadystatechange=function(){if(xhr.readyState==4&&xhr.status==200){if(!isNaN(+xhr.responseText)&&+xhr.responseText!=lastupdate){showloading();lastupdate=+xhr.responseText;var select=document.getElementById('hourtest');select.innerHTML="";var t=lastupdate;var o=+options_n+1;if(type=="forecast")o=18;while(o--){var opt=document.createElement('option');opt.value="?time="+yyyymmddhhmm(t)+token+(type=="forecast"?"&type=forecast&"+lastupdate:"");opt.innerHTML=t;select.appendChild(opt);t-=300;}
var current_index=document.getElementById("hour").selectedIndex;var current_value=document.getElementById("hour").value;SelectToTime();if(document.getElementById("ab").value=="a"){if(current_index>1){document.getElementById("hour").value=current_value;if(document.getElementById("hour").value!=current_value){document.getElementById("hour").selectedIndex=document.getElementById("hour").length-1;}}
update();}}}}
if(type!="forecast")xhr.open('GET',"./xhrv2/lastupdate",true);else xhr.open('GET',"./xhrv2/lastupdate_forecast",true);xhr.send(null);}
optionrange();function checksittings(){document.getElementById("forecast").checked=(localStorage.sittings_forecast=='true');document.getElementById("arrows").checked=(localStorage.sittings_arrows=='true');document.getElementById("speeds").checked=(localStorage.sittings_speeds=='true');document.getElementById("background").checked=(localStorage.sittings_background=='true');document.getElementById("thqafi").checked=(localStorage.thqafi=='true');document.getElementById("gcs").checked=(localStorage.gcs=='true');document.getElementById("water").checked=(localStorage.water=='true');document.getElementById("clouds").checked=(localStorage.clouds!='false');document.getElementById("eradar").checked=(localStorage.eradar=='true');document.getElementById("autoopacity").checked=(localStorage.auto_opacity!='false');document.getElementById("tile").value=(getvalue("tile")||'https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png');document.getElementById("speed").value=(localStorage.speed||50);document.getElementById("gif_speed").value=(localStorage.gif_speed||45);document.getElementById("gif_range").value=(localStorage.gif_range||2);document.getElementById("options_n").value=(localStorage.options_n||12);document.getElementById("input-opacity").value=(localStorage.opacity_s||70);document.getElementById("fullscreen").checked=(localStorage.sittings_fullscreen=='true');document.getElementById("search").checked=(localStorage.search!='false');document.getElementById("myloc").checked=(localStorage.myloc!='false');document.getElementById("dayandnight").checked=(localStorage.sittings_dayandnight=='true');document.getElementById("detectRetina").checked=(localStorage.detectRetina!='false');}
function changetile(){attribution='<a href="http://leafletjs.com" title="A JS library for interactive maps">Leaflet</a>';if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png'){attribution+=' | Map style: &copy; <a href="https://opentopomap.org/">OpenTopoMap</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; senzam.oz, a.s.';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'){attribution+=' | Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">Humanitarian OpenStreetMap Team</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='http://i{hash}.wikimapia.org/?x={x}&y={y}&zoom={z}&r=7071412&type=&lng=10'){attribution+=' | &copy; <a href="http://wikimapia.org/" target="_blank">wikimapia</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/meteored_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; <a href="https://www.meteored.com/">meteored.com</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png?lang=ar'){attribution+=' | &copy; <a href="https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; <a href="https://www.maptiler.com/copyright/">© MapTiler</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';localStorage.clouds=true;document.getElementById("clouds").checked=true;}else{attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}
check_clouds();attribution+=' | &copy; <a href="https://www.yanbuweather.com/">yanbuweather.com</a>';attribution+=' | <a href="https://www.rainviewer.com/sources.html">Radar data sources</a>';map.attributionControl.setPrefix(attribution);attr=document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML;document.getElementsByClassName("leaflet-control-attribution")[0].style.background="rgba(0,0,0,0)";athr='<a href="#" onclick="showattr()"><img src="leaflet/info.svg" style=" width: 16px; opacity: 0.7;box-shadow: inset 0px 0px 19px 0px black; border-radius: 20px; "></a>';map.attributionControl.setPrefix(athr);if(typeof Layer!=='undefined')map.removeLayer(Layer);Layer=L.tileLayer.fallback(SourceTileURL((getvalue("tile")||'https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png')),{detectRetina:localStorage.detectRetina!="false",maxZoom:18,hash:function(data){return data.x%4+(data.y%4)*4;}});map.addLayer(Layer);if(typeof Layer2!=='undefined')map.removeLayer(Layer2);setTimeout(function(){if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){if(typeof Layer2!=='undefined')map.removeLayer(Layer2);Layer2=L.tileLayer.fallback(SourceTileURL('https://www.yanbuweather.com/pages/RainRadar/darkb_tiles/img/{z}-{x}-{y}.png'),{detectRetina:localStorage.detectRetina!="false",maxZoom:18,hash:function(data){return data.x%4+(data.y%4)*4;},zIndex:999});map.addLayer(Layer2);}},5000);if(document.getElementById("ab").value=="a")update();check_water();}
maps={"Yanbu":[36.27970896758124,40.384614853404,25.94024580754594,22.41466930717887],"Gassim":[41.94163126700256,46.13077686878875,28.11950254467146,24.60349761799086],"Abha":[40.93768536690105,44.9029501269149,20.04058774133099,16.52239069362039],"Albaha":[39.91518173575686,43.87860466430367,22.0992331863779,18.59691523055435],"Dammam":[48.11986938743279,52.16970146893773,28.32012044163627,24.82589973402562],"Dawadmi":[42.32656772401545,46.4919853355924,26.24990867260398,22.73619697525762],"Hail":[39.86846703110225,44.06433161250928,29.24405189738772,25.72062210717581],"Jazan":[40.84888237822055,44.81386673026933,18.67761799942703,15.21067372035049],"Jeddah":[37.42234928403259,41.46558852344175,23.53954067967936,20.01582419145118],"Jouf":[38.24569168961052,42.53427138361371,31.60053790400627,28.07280272954911],"Riyadh":[44.97241001915098,49.02224210065592,26.7287820061394,23.23456129852875],"Tabuk":[34.76745133019412,39.00289399788618,30.19478024408654,26.645751312023],"Taif":[38.83818146503008,42.76910718044013,23.3083540975543,19.77986644560621,]};currnet_map='none';function check_topo(element){if(typeof topotiles!=='undefined')map.removeLayer(topotiles);if(element)
if(element.id=="thqafi"){if(element.checked){document.getElementById("gcs").checked=localStorage.gcs=false;}}else if(element.id=="gcs"){if(element.checked){document.getElementById("thqafi").checked=localStorage.thqafi=false;}}
if(localStorage.thqafi!="true"&&localStorage.gcs!="true"){return;}
var url;if(localStorage.thqafi=="true"){url="https://www.yanbuweather.com/pages/RainRadar/athagafy_tiles/img/{z}-{x}-{y}.gif";}else if(localStorage.gcs=="true"){url="https://www.yanbuweather.com/pages/RainRadar/gcs_tiles/img/{z}-{x}-{y}.gif";}else{return;}
topotiles=L.tileLayer.fallback(url,{detectRetina:true,minZoom:7.5,maxNativeZoom:10,maxZoom:19,zIndex:2});map.addLayer(topotiles);}
check_topo();function check_water(element){if(typeof watertiles!=='undefined')map.removeLayer(watertiles);if(localStorage.water!="true"){return;}
var url="https://www.yanbuweather.com/pages/RainRadar/water_tiles/img/{z}-{x}-{y}.png";if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){var oo=0.3;}else{var oo=0.8;}
watertiles=L.tileLayer.fallback(url,{detectRetina:localStorage.detectRetina!="false",minZoom:7.5,maxNativeZoom:11,maxZoom:19,opacity:oo,zIndex:4});map.addLayer(watertiles);}
check_water();function check_clouds(){if(typeof clouds!=='undefined')map.removeLayer(clouds);if(localStorage.clouds=="false"){return;}
var url="getclouds.php"+document.getElementById("hour").value;clouds=L.imageOverlay(url,imageBounds,{opacity:0.8,zIndex:3,className:'cloud'});clouds.addTo(map);}
var stateChangingButton=L.easyButton({states:[{stateName:'pause',icon:'fa-play',title:'متحرك',onClick:function(btn,map){op();btn.state('play');}},{stateName:'play',icon:'fa-pause',title:'ثابت',onClick:function(btn,map){op();btn.state('pause');}}]});stateChangingButton.addTo(map);function getlocalDateTimeformat(date){var options={weekday:"long",year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"numeric"};return date.toLocaleDateString(false,options)+"، "+/\((.*)\)/.exec(new Date().toString())[1]+"";}
function getymdhi(){var U=document.getElementById("hourtest2")[document.getElementById("hourtest").selectedIndex].innerHTML;var x=new Date(U*1000);var y=x.getFullYear().toString();var m=(x.getMonth()+1).toString();var d=x.getDate().toString();var h=x.getHours().toString();var i=x.getMinutes().toString();(d.length==1)&&(d='0'+d);(m.length==1)&&(m='0'+m);(h.length==1)&&(h='0'+h);(i.length==1)&&(i='0'+i);var yyyymmdd=y+"-"+m+"-"+d+" "+h+i;return yyyymmdd;}
function getCaption(){var U=document.getElementById("hourtest2")[document.getElementById("hourtest").selectedIndex].innerHTML;var d=new Date(U*1000);return getlocalDateTimeformat(d);}
DPngT=0;DGifT=0;var customControl=L.Control.extend({options:{position:'topright'},onAdd:function(map){var container=L.DomUtil.create('div','leaflet-bar leaflet-control leaflet-control-custom');container.style.backgroundColor='white';container.style.backgroundImage="url(leaflet/save.svg)";container.style.backgroundSize="75%";container.style.backgroundPosition="50% 50%";container.style.backgroundRepeat="no-repeat";container.style.width='30px';container.style.height='30px';container.style.cursor='pointer';container.onclick=function(){if(new Date().getTime()/1000-DPngT<=30){var wait=30-Math.round(new Date().getTime()/1000-DPngT);if(new Date().getTime()/1000-DPngT>7)alert("يرجى الانتظار مدة "+wait+" ثانية قبل تحميل صورة أخرى.");return;}
DPngT=new Date().getTime()/1000;var href="./download/image.php";href+=document.getElementById("hour").value;var bounds=map.getBounds(),northWest=bounds.getNorthWest(),southEast=bounds.getSouthEast();href+="&bounds=";href+=fixlng(northWest.lng,-1)+",";href+=fixlat(southEast.lat,1)+",";href+=fixlng(southEast.lng,1)+",";href+=fixlat(northWest.lat,-1);var tile='mapy.cz';if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png'){tile='opentopomap';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png'){tile='mapy.cz';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/tracestrack_tiles/img/{z}-{x}-{y}.png'){tile='tracestrack';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'){tile='openstreetmap';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'){tile='openstreetmap.hot';}else if(localStorage.tile=='http://i{hash}.wikimapia.org/?x={x}&y={y}&zoom={z}&r=7071412&type=&lng=10'){tile='wikimapia';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/meteored_tiles/img/{z}-{x}-{y}.png'){tile='meteored';}else if(localStorage.tile=='https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png?lang=ar'){tile='wikimedia';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){tile='dark';}
href+="&tiletype="+tile;href+="&alpha="+!(localStorage.sittings_background=='true');href+="&opacity="+getcurrentOpacity()*100;try{href+="&timezone="+(Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC");}catch(a){}
href+="&thqafi="+(localStorage.thqafi=="true");href+="&gcs="+(localStorage.gcs=="true");href+="&water="+(localStorage.water=="true");href+="&clouds="+(localStorage.clouds!="false");href+="&eradar="+(localStorage.eradar!="false");href+="&verify=true";window.open(href,'_blank');}
return container;}});map.addControl(new customControl());var customControl2=L.Control.extend({options:{position:'topright'},onAdd:function(map){var container=L.DomUtil.create('div','leaflet-bar leaflet-control leaflet-control-custom');container.style.backgroundColor='white';container.style.backgroundImage="url(leaflet/savegif.svg?2)";container.style.backgroundSize="75%";container.style.backgroundPosition="50% 50%";container.style.backgroundRepeat="no-repeat";container.style.width='30px';container.style.height='30px';container.style.cursor='pointer';container.onclick=function(){if(new Date().getTime()/1000-DGifT<=60){var wait=60-Math.round(new Date().getTime()/1000-DGifT);if(new Date().getTime()/1000-DGifT>7)alert("يرجى الانتظار مدة "+wait+" ثانية قبل تحميل صورة أخرى.");return;}
DGifT=new Date().getTime()/1000;var href="./download/animated.php";href+=document.getElementById("hour").value;var bounds=map.getBounds(),northWest=bounds.getNorthWest(),southEast=bounds.getSouthEast();href+="&bounds=";href+=fixlng(northWest.lng,-1)+",";href+=fixlat(southEast.lat,1)+",";href+=fixlng(southEast.lng,1)+",";href+=fixlat(northWest.lat,-1);var tile='mapy.cz';if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png'){tile='opentopomap';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png'){tile='mapy.cz';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/tracestrack_tiles/img/{z}-{x}-{y}.png'){tile='tracestrack';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'){tile='openstreetmap';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'){tile='openstreetmap.hot';}else if(localStorage.tile=='http://i{hash}.wikimapia.org/?x={x}&y={y}&zoom={z}&r=7071412&type=&lng=10'){tile='wikimapia';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/meteored_tiles/img/{z}-{x}-{y}.png'){tile='meteored';}else if(localStorage.tile=='https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png?lang=ar'){tile='wikimedia';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){tile='dark';}
href+="&tiletype="+tile;href+="&alpha="+!(localStorage.sittings_background=='true');href+="&opacity="+getcurrentOpacity()*100;try{href+="&timezone="+(Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC");}catch(a){}
href+="&hours="+(localStorage.gif_range||2);href+="&speed="+(localStorage.gif_speed||45);href+="&thqafi="+(localStorage.thqafi=="true");href+="&gcs="+(localStorage.gcs=="true");href+="&water="+(localStorage.water=="true");href+="&clouds="+(localStorage.clouds!="false");href+="&eradar="+(localStorage.eradar!="false");href+="&verify=true";window.open(href,'_blank');}
return container;}});map.addControl(new customControl2());function showattr(){document.getElementsByClassName("leaflet-control-attribution")[0].style.background="rgba(255,255,255,0.7)";document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML=attr;setTimeout(function(){document.getElementsByClassName("leaflet-control-attribution")[0].style.background="rgba(0,0,0,0)";document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML=athr;history.pushState({},null,"./");},10000);}
var callBack=function(){attribution='<a href="http://leafletjs.com" title="A JS library for interactive maps">Leaflet</a>';if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png'){attribution+=' | Map style: &copy; <a href="https://opentopomap.org/">OpenTopoMap</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; senzam.oz, a.s.';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/tracestrack_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; tracestrack.com';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'){attribution+=' | Tiles courtesy of <a href="http://hot.openstreetmap.org/" target="_blank">Humanitarian OpenStreetMap Team</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='http://i{hash}.wikimapia.org/?x={x}&y={y}&zoom={z}&r=7071412&type=&lng=10'){attribution+=' | &copy; <a href="http://wikimapia.org/" target="_blank">wikimapia</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/meteored_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; <a href="https://www.meteored.com/">meteored.com</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png?lang=ar'){attribution+=' | &copy; <a href="https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else if(localStorage.tile=='https://www.yanbuweather.com/pages/RainRadar/darka_tiles/img/{z}-{x}-{y}.png'){attribution+=' | &copy; <a href="https://www.maptiler.com/copyright/">© MapTiler</a>';attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}else{attribution+=' | &copy; <a href="https://www.openstreetmap.org/copyright">مساهمو خريطة الشارع المفتوحة</a>';}
attribution+=' | &copy; <a href="https://www.yanbuweather.com/">yanbuweather.com</a>';attribution+=' | <a href="https://www.rainviewer.com/sources.html">Radar data sources</a>';map.attributionControl.setPrefix(attribution);attr=document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML;document.getElementsByClassName("leaflet-control-attribution")[0].style.background="rgba(0,0,0,0)";athr='<a href="#" onclick="showattr()"><img src="leaflet/info.svg" style=" width: 16px; opacity: 0.7;box-shadow: inset 0px 0px 19px 0px black; border-radius: 20px; "></a>';document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML=athr;var css='';var head=document.head||document.getElementsByTagName('head')[0],style=document.createElement('style');head.appendChild(style);if($('.leaflet-tile-container img')[0].style.height=="256px"){css=".leaflet-tile-container img {width: 256.5px !important; height: 256.5px !important;}";}else if($('.leaflet-tile-container img')[0].style.height=="128px"){css=".leaflet-tile-container img {width: 128.5px !important; height: 128.5px !important;}";}
style.type='text/css';if(style.styleSheet){style.styleSheet.cssText=css;}else{style.appendChild(document.createTextNode(css));}};map.whenReady(callBack);setInterval(function(){var timediff=new Date().getTime()-(+lastupdate*1000);if(type=="real"&&timediff>0&&timediff<300000){return;}
if(typeof xhr!='undefined'&&xhr.readyState!=4){return;}
var options_n=localStorage.options_n||12;setCookie("options_n",options_n);xhr=XMLhttpreq;xhr.onreadystatechange=function(){if(xhr.readyState==4&&xhr.status==200){if(!isNaN(+xhr.responseText)&&+xhr.responseText!=lastupdate){showloading();lastupdate=+xhr.responseText;var select=document.getElementById('hourtest');select.innerHTML="";var t=lastupdate;var o=+options_n+1;if(type=="forecast")o=18;while(o--){var opt=document.createElement('option');opt.value="?time="+yyyymmddhhmm(t)+token+(type=="forecast"?"&type=forecast&"+lastupdate:"");opt.innerHTML=t;select.appendChild(opt);t-=300;}
var img=new Image;img.onload=function(){hideloading();var current_index=document.getElementById("hour").selectedIndex;var current_value=document.getElementById("hour").value;SelectToTime();if(document.getElementById("ab").value=="a"){if(current_index>1){document.getElementById("hour").value=current_value;if(document.getElementById("hour").value!=current_value){document.getElementById("hour").selectedIndex=document.getElementById("hour").length-1;}}
update();}}
img.onerror=function(){hideloading();loading=false;}
img.src=getRadarUrl()+document.getElementById("hourtest")[0].value+"&alpha="+(localStorage.sittings_background!='true');}}}
if(type!="forecast")xhr.open('GET',"./xhrv2/lastupdate",true);else xhr.open('GET',"./xhrv2/lastupdate_forecast",true);xhr.send(null);},6E3);function g(s,e,p){return(p-s)/(e-s);}
function fixlat(lat,plus){if(!plus)plus=0;imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];var minY=(1-(Math.log(Math.tan((Math.PI/180)*imageBounds[1][0])+1/Math.cos((Math.PI/180)*imageBounds[1][0]))/Math.PI))/2;var maxY=(1-(Math.log(Math.tan((Math.PI/180)*imageBounds[0][0])+1/Math.cos((Math.PI/180)*imageBounds[0][0]))/Math.PI))/2;var yp=(1-(Math.log(Math.tan((Math.PI/180)*lat)+1/Math.cos((Math.PI/180)*lat))/Math.PI))/2;y=Math.floor(g(minY,maxY,yp)*4500+plus)/4500;yp=minY*-y+minY+maxY*y;lat=(180/Math.PI)*(Math.atan(Math.sinh(Math.PI*(1-2*yp))));return lat;}
function fixlng(lng,plus){if(!plus)plus=0;imageBounds=[[11.178401873712,33.75],[34.307143856288,61.875]];var x=Math.floor(g(imageBounds[0][1],imageBounds[1][1],lng)*5000+plus)/5000;lng=imageBounds[0][1]*-x+imageBounds[0][1]+imageBounds[1][1]*x;return lng;}
function getvalue(key){try{var s=localStorage.getItem(key);if(s!=null&&s!=false&&s.length>0&&s.indexOf("http")!=-1&&s.indexOf("//")!=-1)return s;return false;}catch(a){}
return false;}
function yyyymmddhhmm(t){var date=new Date(t*1000);var dateStr=date.getUTCFullYear()+
"-"+("00"+(date.getUTCMonth()+1)).slice(-2)+
"-"+("00"+date.getUTCDate()).slice(-2)+
"-"+("00"+date.getUTCHours()).slice(-2)+
"-"+("00"+date.getUTCMinutes()).slice(-2);return dateStr;}
function SourceTileURL(s){return s.replace("https://www.yanbuweather.com/pages/RainRadar/mapy.cz_tiles/img/{z}-{x}-{y}.png","https://tiles.windy.com/v1/maptiles/outdoor/256%402x/{z}/{x}/{y}/?lang=en").replace("https://www.yanbuweather.com/pages/RainRadar/opentopomap_tiles/img/{z}-{x}-{y}.png","https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png");}
function cacheFor(minutes){var a=new Date().getTime();a-=a%(minutes*60*1000);return "&hit="+a;}
if(localStorage.eradar!="true"){confirm("الرادار متعطل حاليا.. سيتم تفعيل بديل الرادار");localStorage.eradar=true;update();}
